--Retrieve all hotels:
SELECT * FROM Hotel;

--Find available rooms in a specific hotel:
SELECT * FROM Room WHERE hotel_id = <hotel_id> AND availability = 'available';

--Get reservation details for a specific guest:
SELECT * FROM Reservation WHERE guest_id = <guest_id>;

--Find all reservations for a specific room:
SELECT * FROM Reservation WHERE room_number = <room_number>;
--List all guests who have reservations in a specific hotel:
SELECT DISTINCT Guest.* FROM Guest
JOIN Reservation ON Guest.guest_id = Reservation.guest_id WHERE Reservation.room_number IN (SELECT room_number FROM Room WHERE hotel_id = <hotel_id>);

--Find employees in a specific department:
SELECT * FROM Employee WHERE department ='<department_name>';

--Retrieve services offered by the hotel:
SELECT * FROM Service;

-- Get the total number of reservations for each room type:
SELECT type, COUNT(*) AS reservation_count FROM Room JOIN Reservation
ON Room.room_number = Reservation.room_number GROUP BY type;

--Find the most expensive room in a specific hotel:
SELECT * FROM Room WHERE hotel_id = <hotel_id> ORDER BY price
DESC LIMIT 1;

--Retrieve the number of available rooms in each hotel:
SELECT hotel_id, COUNT(*) AS available_rooms_count FROM Room
WHERE availability = 'available' GROUP BY hotel_id;

--Get the average price for each room type:
SELECT type, AVG(price) AS average_price FROM Room
GROUP BY type;

--Find employees with managerial positions:
SELECT * FROM Employee WHERE position LIKE '%manager%';

--List rooms with no reservations:
SELECT * FROM Room WHERE room_number NOT IN (SELECT DISTINCT room_number FROM Reservation);

--Get the top 5 guests with the highest total spending:
SELECT Guest.guest_id, Guest.name, SUM(Room.price) AS total_spending FROM Guest
JOIN Reservation ON Guest.guest_id = Reservation.guest_id JOIN Room ON Reservation.room_number = Room.room_number GROUP BY Guest.guest_id
ORDER BY total_spending DESC LIMIT 5;

--Retrieve the total number of reservations made by a specific guest:
SELECT COUNT(*) AS total_reservations FROM Reservation
WHERE guest_id = <guest_id>;

--Retrieve the guest details along with the corresponding hotel and room information for a specific reservation:
SELECT Guest.*, Hotel.name AS hotel_name, Room.* FROM Guest
INNER JOIN Reservation ON Guest.guest_id = Reservation.guest_id INNER JOIN Room ON Reservation.room_number = Room.room_number INNER JOIN Hotel ON Room.hotel_id = Hotel.hotel_id
WHERE Reservation.reservation_id = <reservation_id>;

--Retrieve the total revenue generated by a specific hotel:
SELECT SUM(Room.price) AS total_revenue FROM Room
WHERE Room.hotel_id = <hotel_id>;

--Update the availability of a specific room:
UPDATE ROOM SET availability
WHERE room_number = <room_number>;
